# 1. Introduction to Python: Exercise Solutions

In [1]:
import numpy as np

##  Lists and loops
Create the following lists, possibly in multiple ways.

1) odd positive integers below 20.

In [2]:
N = 20
j = 0
y = []
x = [x + 1 for x in range(N)]
for i in range (N): 
    if x[i]%2!=0: 
        y.append(x[i])

print (y)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [3]:
odd = []
for i in range(20):
    if i % 2 == 1:
        odd = odd + [i]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [4]:
A = []
for i in range(0,10):
    A = A + [2*i+1]
print(A)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [5]:
odd = [i for i in range (1,21,2)]
print(odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [6]:
print(list(range(1,21,2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


2) sums from 1 to n, for up to n=10.

In [7]:
n = 10 
a = [a+1 for a in range (n)]
for i in range (1,n):
    a[i] = a[i-1] + a[i]
print(a)

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


In [8]:
sums = []
sum_all = 0
for i in range(1, 11):
    sum_all += i
    sums.append(sum_all)
print(sums)

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]


In [9]:
k=[sum(list(range(1,i))) for i in range(2,12)]
k

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55]

3) prime numbers below n=20.

In [10]:
n = 20
A = []
for i in range(2,n):
    count = 0
    for j in range(2,i):
        if(i%j==0):
            count = 1        
    if(count==0):
        A.append(i)
print(A)

[2, 3, 5, 7, 11, 13, 17, 19]


In [11]:
n = 20
y = []
for i in range(2,n):
    for j in range (2,i):
        if i%j == 0:
            break
    else: # if the for loop doesn't break
        y.append(i)
print(y)

[2, 3, 5, 7, 11, 13, 17, 19]


In [12]:
n = 20
list_d = list()
for i in range(2,n):
    if all(i%j!=0 for j in range(2,i)):
        list_d.append(i)
print(list_d)

[2, 3, 5, 7, 11, 13, 17, 19]


In [13]:
import sympy
list(sympy.primerange(0, 20))

[2, 3, 5, 7, 11, 13, 17, 19]

4) n=10 random numbers between 0 and k=5.  
(use np.random.randint())

In [14]:
n = 10
k = 5
r = []
for i in range(n):
    r.append(np.random.randint(k))
r

[3, 3, 3, 3, 2, 1, 3, 0, 3, 2]

In [15]:
n = 10
k = 5
[ np.random.randint(k) for i in range(n)]

[1, 0, 2, 0, 4, 3, 4, 1, 0, 0]

In [16]:
np.random.randint(0, 5, 10)

array([1, 1, 1, 1, 3, 0, 1, 3, 2, 4])

In [17]:
np.random.randint(5, size=10)

array([1, 3, 1, 4, 3, 0, 2, 4, 4, 0])

5) from two lists of the same length, make a list with the larger of the items at the same position.

In [18]:
n = 10 
min = 0
max = 5
x = np.random.randint(min, max, n)
y = np.random.randint(min, max, n)
print(x, y)
z = np.zeros(n)
for i in range(n):
    if x[i] > y[i]:
        z[i] = x[i]
    else:
        z[i] = y[i] 
print(z)

[3 1 2 1 2 3 4 2 2 2] [0 4 4 1 3 0 2 4 2 4]
[3. 4. 4. 1. 3. 3. 4. 4. 2. 4.]


In [19]:
n = 10
x = np.arange(n) # 0 to n-1
y = np.arange(n,0,-1)  # n to 1
z = [ np.max((x[i], y[i])) for i in range(n)]
np.array(z)

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])

In [20]:
np.max([x,y], axis=0)

array([10,  9,  8,  7,  6,  5,  6,  7,  8,  9])

6) from a random list with 7 items, find the median 

In [21]:
n = 7
a = np.random.randint(0, 10, n)
print(a)
sorted_a = sorted(a)
print(sorted_a)
i = int((len(a))/2)
sorted_a[i]

[2 8 3 9 0 2 7]
[0, 2, 2, 3, 7, 8, 9]


3

In [22]:
a = np.random.randint(0, 10, n)
print(a)
a.sort()
print(a)
a[int((len(a))/2)]

[8 3 5 7 7 2 8]
[2 3 5 7 7 8 8]


7

In [23]:
np.median(a)

7.0

## Arrays and matrices

1) an m-by-n matrix with random integers from 0 to k.

In [24]:
# for example
m = 3
n = 4
k = 10
matrix = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        matrix[i,j] = np.random.randint(k)
print(matrix)

[[8. 1. 0. 5.]
 [8. 7. 5. 0.]
 [0. 0. 0. 0.]]


In [25]:
m, n, k = 3, 4, 10
A = [[np.random.randint(0,k) for j in range(n)] for i in range(m)]
np.array(A)

array([[6, 6, 8, 5],
       [7, 9, 0, 4],
       [6, 6, 1, 4]])

In [26]:
m = 3
n = 4
k = 10
np.random.randint(0, k, (m,n))

array([[1, 2, 0, 7],
       [9, 9, 5, 8],
       [0, 5, 0, 2]])

2) from a matrix, make a sub matrix of items in odd rows and even columns.

In [27]:
m = 3
n = 4
k = 10
A = np.random.randint(0, k, (m,n))
print(A)
B = []
for i in range(0, m, 2):
    b = []
    for j in range(1, n, 2):
        b.append(A[i,j])
    B.append(b)
print(np.array(B))

[[5 4 9 8]
 [1 0 0 3]
 [6 1 3 7]]
[[4 8]
 [1 7]]


In [28]:
m, n, k = 3, 4, 10
A = np.random.randint(0, k, (m,n))
print(A)
B = A[::2, 1::2]
print(B)

[[4 8 7 4]
 [3 3 6 7]
 [9 6 2 3]]
[[8 4]
 [6 3]]


3) make a m-by-n matrix with (i,j) component as i/j.

In [29]:
m = 3
n = 4
A = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        A[i,j] = (i+1)/(j+1)
print(A)

[[1.         0.5        0.33333333 0.25      ]
 [2.         1.         0.66666667 0.5       ]
 [3.         1.5        1.         0.75      ]]


In [30]:
A = [[(i+1)/(j+1) for j in range(n)] for i in range(m)]
np.array(A)

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [2.        , 1.        , 0.66666667, 0.5       ],
       [3.        , 1.5       , 1.        , 0.75      ]])

4) for a n-by-n matrix $A$, compute the k-th power $A^k$.

In [31]:
A = np.array([[2,0],[0,3]])
print(A)
k = 3
B = A
if k>1:
    for i in range(k-1):
        B = B @ A
print(B)

[[2 0]
 [0 3]]
[[ 8  0]
 [ 0 27]]


In [32]:
n = 3
A = np.diag(np.random.randn(n))
print(A)
k = 2
B = np.eye(len(A))
for i in range(k):
    B = B @ A
print(B)

[[ 0.21492797  0.          0.        ]
 [ 0.         -2.40175617  0.        ]
 [ 0.          0.          0.87200628]]
[[0.04619403 0.         0.        ]
 [0.         5.76843271 0.        ]
 [0.         0.         0.76039496]]
